# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (LARAGON)
# ==========================================

# 1. La URL de conexión (Puerto 3306 es Laragon)
# Asegúrate de haber creado la base de datos 'almacerca_db' en HeidiSQL antes
spring.datasource.url=jdbc:mysql://localhost:3306/almacerca?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# 2. Credenciales (Por defecto en Laragon)
spring.datasource.username=root
spring.datasource.password=

# 3. El Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# COMPORTAMIENTO DE JPA (HIBERNATE)
# ==========================================

# Crea las tablas automáticamente si no existen.
# Si cambias tu código Java, actualiza las tablas sin borrar los datos.
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola las consultas SQL que se hacen por detrás (Útil para depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Especificamos que hablamos el idioma de MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
